# Web Scraping with Python

This project demonstrates how to extract structured information from a webpage using Python.

### Tools Used

* Python
* Requests
* BeautifulSoup
* LXML
* Pandas

### Objective

To fetch webpage content, parse HTML elements, and extract useful information into a structured format.

### Scraping Considerations

* Check the website's Terms and Conditions before scraping.
* Avoid sending too many requests in a short period.
* Monitor scraping activity and handle requests responsibly.
* Clean and preprocess the extracted data before analysis.
* Configure the scraper according to the website structure.

In [1]:
# beautifulsoup
# lxml parser
# requests

In [2]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.3-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
Downloading lxml-6.1.3-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 2.8 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.0 MB 5.0 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 4.9 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.3

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

## Target Website

The project extracts archive information from Student News Daily.

**Source:** Student News Daily — Daily News Article Archive

In [4]:
url = 'https://www.studentnewsdaily.com/archive/daily-news-article/'

## Fetch and Parse Webpage

The webpage is accessed using the Requests library, and BeautifulSoup is used to parse the HTML content.

In [22]:
response = requests.get(url, timeout=10)
response.raise_for_status()

# Parse the HTML content
soup = BeautifulSoup(response.content, "lxml")

In [23]:
content = soup.find("div", class_="col-md-10 col-lg-10 col-xl-10")

print(content is not None)

True

## Data Extraction

The scraper extracts article information from the webpage and stores the results in a structured Pandas DataFrame.

In [24]:
articles = content.find_all("p")

for article in articles[:10]:
    print(article.get_text(" ", strip=True))

9/24/2026 - Trump greets China’s Xi at airport in historic move — as nations agree to trade truce to kick off high-stakes DC visit - NY Post
9/22/2026 - Trump at the UN: “Iran will never have a nuclear weapon”
9/17/2026 - Justice Department arrests 12 in $10M childcare fraud scheme - Daily Wire
9/15/2026 - With table set for Senate battle, here are the races to watch - Just the News
9/10/2026 - Drone activity at U.S.-Mexico border drops 75% after U.S. uses laser weapon - CBS News
9/8/2026 - 81 members of Puerto Rico gang charged in major drug trafficking case - TNND at ABC News4
9/3/2026 - Twenty-five years later – what you should know about 9/11
8/18/2026 - 11 arrested in sham marriage scheme giving Chinese nationals green cards - News Nation
6/1/2026 - The miracle of D-Day - Daily Mail
5/22/2026 - Memorial Day 2026 - USMemorialDay.org

In [25]:
data = []

for article in articles:
    text = article.get_text(" ", strip=True)
    data.append(text)

df = pd.DataFrame(data, columns=["article"])

df.head(10)

                                             article
0  9/24/2026 - Trump greets China’s Xi at airport...
1  9/22/2026 - Trump at the UN: “Iran will never ...
2  9/17/2026 - Justice Department arrests 12 in $...
3  9/15/2026 - With table set for Senate battle, ...
4  9/10/2026 - Drone activity at U.S.-Mexico bord...
5  9/8/2026 - 81 members of Puerto Rico gang char...
6  9/3/2026 - Twenty-five years later – what you ...
7  8/18/2026 - 11 arrested in sham marriage schem...
8       6/1/2026 - The miracle of D-Day - Daily Mail
9  5/22/2026 - Memorial Day 2026 - USMemorialDay.org

In [26]:
df[["date", "article_title"]] = df["article"].str.split(" - ", n=1, expand=True)

df = df[["date", "article_title"]]

df.head(10)

        date                                      article_title
0  9/24/2026  Trump greets China’s Xi at airport in historic...
1  9/22/2026  Trump at the UN: “Iran will never have a nucle...
2  9/17/2026  Justice Department arrests 12 in $10M childcar...
3  9/15/2026  With table set for Senate battle, here are the...
4  9/10/2026  Drone activity at U.S.-Mexico border drops 75%...
5   9/8/2026  81 members of Puerto Rico gang charged in majo...
6   9/3/2026  Twenty-five years later – what you should know...
7  8/18/2026  11 arrested in sham marriage scheme giving Chi...
8   6/1/2026                  The miracle of D-Day - Daily Mail
9  5/22/2026              Memorial Day 2026 - USMemorialDay.org

In [27]:
df["date"] = pd.to_datetime(df["date"])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           500 non-null    datetime64[us]
 1   article_title  500 non-null    str
dtypes: datetime64[us](1), str(1)
memory usage: 7.9 KB

In [28]:
df.isnull().sum()

date             0
article_title    0
dtype: int64

In [29]:
print(f"Total articles scraped: {len(df)}")

Total articles scraped: 500

## Exported Dataset

The cleaned and structured data is exported as a CSV file for further analysis or reuse.

In [30]:
df.to_csv("scraped_articles.csv", index=False)

print("CSV file saved successfully!")

CSV file saved successfully!

In [31]:
import os

print(os.path.exists("scraped_articles.csv"))

True

In [32]:
df.head(10)

        date                                      article_title
0 2026-09-24  Trump greets China’s Xi at airport in historic...
1 2026-09-22  Trump at the UN: “Iran will never have a nucle...
2 2026-09-17  Justice Department arrests 12 in $10M childcar...
3 2026-09-15  With table set for Senate battle, here are the...
4 2026-09-10  Drone activity at U.S.-Mexico border drops 75%...
5 2026-09-08  81 members of Puerto Rico gang charged in majo...
6 2026-09-03  Twenty-five years later – what you should know...
7 2026-08-18  11 arrested in sham marriage scheme giving Chi...
8 2026-06-01                  The miracle of D-Day - Daily Mail
9 2026-05-22              Memorial Day 2026 - USMemorialDay.org

## Data Summary

The final dataset contains 500 scraped articles with their publication dates and article titles.

In [34]:
import pandas as pd

csv_df = pd.read_csv("scraped_articles.csv")

print(f"CSV rows: {len(csv_df)}")
print(f"CSV columns: {list(csv_df.columns)}")

CSV rows: 500
CSV columns: ['date', 'article_title']